# .pre-commit-config.yaml
---
repos:
  - repo: https://github.com/python/black.git
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: ['--skip-string-normalization', '--line-length', '79']
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
        language_version: python3
  - repo: https://gitlab.com/pycqa/pydocstyle.git
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - toml>=0.10.2
        language_version: python3
        files: ^examples/ ^scripts/ ^heykube/